# Generated by Django 3.2.13 on 2022-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='uploads/profile_pictures/default.jpg', upload_to='uploads/profile_pictures/'),
        ),
    ]
