version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - dev.env
  web:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    image: django_app:latest-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./data/web:/vol/web
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db
