version: "3.9"

services:
  db:
    image: postgres:14.4
    container_name: django_db_prod
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - reverse_proxy
  web:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    image: django_app:latest-prod
    container_name: django_web_prod
    volumes:
      - .:/code
      - ./data/web:/vol/web
    env_file:
      - .env

    depends_on:
      - db
    networks:
      - reverse_proxy

networks:
   reverse_proxy:
      external: true
