version: "3.9"

services:
  db-staging:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - test
  web-staging:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    image: django_app:latest-staging
    volumes:
      - .:/code
      - ./data/web:/vol/web
    env_file:
      - .env

    depends_on:
      - db-staging
    networks:
      - test

networks:
   test:
      external: true
