version: "3.9"

services:
  db-staging:
    image: postgres:14.4
    container_name: django_db_stag
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - reverse_proxy
  web-staging:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    image: django_app:latest-staging
    container_name: django_web_stag
    volumes:
      - .:/code
      - ./data/web:/vol/web
    env_file:
      - .env
    depends_on:
      - db-staging
    networks:
      - reverse_proxy

networks:
   reverse_proxy:
      external: true
