# Generated by Django 3.2.13 on 2022-06-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
