# Generated by Django 3.2.13 on 2022-06-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_time_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='min_n_participants',
        ),
        migrations.AddField(
            model_name='activity',
            name='n_participants',
            field=models.IntegerField(default=0),
        ),
    ]
