# Generated by Django 4.0.6 on 2022-07-05 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_activity_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_activity', to='activities.category'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='activities_voted', to='activities.activityvote'),
        ),
    ]
